name: SHRP Recovery Build - GitHub Runner

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Checkout Workflow
      uses: actions/checkout@v4

    - name: Cleanup Space (Crucial for GitHub Runners)
      run: |
        sudo rm -rf /usr/share/dotnet /etc/mysql /usr/local/lib/android /opt/ghc /usr/local/share/boost
        sudo apt clean
        df -h

    - name: Install Build Packages
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential curl flex g++-multilib gperf gcc-multilib \
        git gnupg gflip libxml2 lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev \
        libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python2
        sudo ln -sf /usr/bin/python2 /usr/bin/python

    - name: Install Repo Tool
      run: |
        mkdir ~/bin && curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Sync SHRP v3_9.0 Source
      run: |
        mkdir workspace && cd workspace
        git config --global user.name "Ansh_m14x"
        git config --global user.email "ansh@example.com"
        # Syncing only required parts to save space
        repo init --depth=1 -u https://github.com/SHRP/manifest.git -b v3_9.0
        repo sync -c -j$(nproc --all) --force-sync --no-tags --no-clone-bundle

    - name: Clone Device Tree
      run: |
        cd workspace
        git clone https://github.com/Ansh-m14x/android_device_oppo_CPH2015 -b main device/oppo/OP4C7D

    - name: Build SHRP
      run: |
        cd workspace
        export ALLOW_MISSING_DEPENDENCIES=true
        export LC_ALL=C
        source build/envsetup.sh
        lunch omni_OP4C7D-eng
        # Guide ke mutabiq mka recoveryimage use karein
        make recoveryimage -j$(nproc --all)

    - name: Upload Recovery Image
      uses: actions/upload-artifact@v4
      with:
        name: SHRP-Recovery-A31
        path: workspace/out/target/product/OP4C7D/recovery.img

    - name: Release Build
      uses: ncipollo/release-action@v1
      with:
        artifacts: "workspace/out/target/product/OP4C7D/recovery.img"
        name: SHRP v3.2 for Oppo A31
        tag: SHRP-${{ github.run_id }}
        token: ${{ secrets.GITHUB_TOKEN }}
        body: "Built by Ansh_m14x using SHRP Manifest v3_9.0"
