name: PBRP Sync Tester

on:
  workflow_dispatch:

jobs:
  test_sync:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Initialize & Sync
      run: |
        mkdir workspace && cd workspace
        git config --global user.name "Ansh_m14x"
        git config --global user.email "ansh@example.com"
        
        # Screenshot wali exact repo aur branch
        repo init --depth=1 -u https://github.com/PitchBlackRecoveryProject/manifest_pb.git -b android-9.0
        
        # Syncing only core repos to save time and check branch validity
        repo sync -c -j$(nproc --all) --force-sync --no-tags --no-clone-bundle
