name: SHRP Recovery Build

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'MANIFEST_URL'
        required: true
        default: 'https://github.com/SHRP/manifest'
      MANIFEST_BRANCH:
        description: 'MANIFEST_BRANCH'
        required: true
        default: 'shrp-12.1'
      DEVICE_TREE_URL:
        description: 'DEVICE_TREE_URL'
        required: true
        default: 'https://github.com/ansh-m14x/android-recovery-OP4C7D'
      DEVICE_TREE_BRANCH:
        description: 'DEVICE_TREE_BRANCH'
        required: true
        default: 'shrp'
      DEVICE_PATH:
        description: 'DEVICE_PATH'
        required: true
        default: 'device/oppo/OP4C7D'
      DEVICE_NAME:
        description: 'DEVICE_NAME'
        required: true
        default: 'OP4C7D'
      MAKEFILE_NAME:
        description: 'MAKEFILE_NAME'
        required: true
        default: 'shrp_OP4C7D'
      BUILD_TARGET:
        description: 'BUILD_TARGET'
        required: true
        default: 'shrp'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - name: Check Out
      uses: actions/checkout@v4

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Install Build Packages (Merged List)
      run: |
        sudo apt-get update
        # Adding Universe for legacy packages
        sudo add-apt-repository universe -y
        sudo apt-get update
        sudo apt-get -y install libncurses5 python2 python3 \
        git ccache automake flex lzop bison gperf build-essential zip curl \
        zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 \
        libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool \
        make optipng maven libssl-dev pwgen libswitch-perl policycoreutils \
        minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 \
        lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip \
        device-tree-compiler libtinfo5
        
        # Ensure 'python' points to 'python2' for TWRP/SHRP scripts
        sudo ln -sf /usr/bin/python2 /usr/bin/python

    - name: Install repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Initialize repo
      run: |
        mkdir workspace
        cd workspace
        git config --global user.name "Ansh"
        git config --global user.email "ansh@example.com"
        repo init --depth=1 -u ${{ github.event.inputs.MANIFEST_URL }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
      id: pwd

    - name: Repo Sync
      run: repo sync -j$(nproc --all) --force-sync --no-tags --no-clone-bundle
      working-directory: workspace

    - name: Clone device tree
      run: git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
      working-directory: workspace

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Building SHRP
      run: |
        cd workspace
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        
        lunch ${{ github.event.inputs.MAKEFILE_NAME }}-eng
        echo "🏗️ Starting Build for ${{ github.event.inputs.DEVICE_NAME }}..."
        mka ${{ github.event.inputs.BUILD_TARGET }} -j$(nproc --all)
      shell: bash

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery.img
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/SHRP*.zip
        name: SHRP-${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
